// Tunisia Governorates and Cities Data
export const tunisiaGovernorates = [
  { id: 'tunis', name: 'تونس' },
  { id: 'ariana', name: 'أريانة' },
  { id: 'ben_arous', name: 'بن عروس' },
  { id: 'manouba', name: 'منوبة' },
  { id: 'nabeul', name: 'نابل' },
  { id: 'zaghouan', name: 'زغوان' },
  { id: 'bizerte', name: 'بنزرت' },
  { id: 'beja', name: 'باجة' },
  { id: 'jendouba', name: 'جندوبة' },
  { id: 'kef', name: 'الكاف' },
  { id: 'siliana', name: 'سليانة' },
  { id: 'kairouan', name: 'القيروان' },
  { id: 'kasserine', name: 'القصرين' },
  { id: 'sidi_bouzid', name: 'سيدي بوزيد' },
  { id: 'sousse', name: 'سوسة' },
  { id: 'monastir', name: 'المنستير' },
  { id: 'mahdia', name: 'المهدية' },
  { id: 'sfax', name: 'صفاقس' },
  { id: 'gafsa', name: 'قفصة' },
  { id: 'tozeur', name: 'توزر' },
  { id: 'kebili', name: 'قبلي' },
  { id: 'gabes', name: 'قابس' },
  { id: 'medenine', name: 'مدنين' },
  { id: 'tatouine', name: 'تطاوين' },
]

export const tunisiaCities: Record<string, string[]> = {
  tunis: [
    'تونس المدينة',
    'باردو',
    'الكرم',
    'سيدي حسين',
    'الكبارية',
    'الزهراء',
    'المروج',
    'باب عليوة',
    'الكبارية',
    'بن عروس',
    'المروج',
  ],
  ariana: [
    'أريانة',
    'رواد',
    'منوبة',
    'قلعة الأندلس',
    'سيدي ثابت',
    'المغيرة',
    'قلعة الأندلس',
  ],
  ben_arous: [
    'بن عروس',
    'رادس',
    'حمام الأنف',
    'فوشانة',
    'المحمدية',
    'المروج',
    'الزهراء',
  ],
  manouba: [
    'منوبة',
    'البطان',
    'دوار هيشر',
    'الجديدة',
    'الكاف',
    'تيبار',
  ],
  nabeul: [
    'نابل',
    'حمامات',
    'قليبية',
    'بني خيار',
    'قربة',
    'المنستير',
  ],
  zaghouan: [
    'زغوان',
    'الناظور',
    'فريانة',
    'صواف',
    'بئر مشارقة',
  ],
  bizerte: [
    'بنزرت',
    'ماتور',
    'ماطر',
    'رأس الجبل',
    'منزل جميل',
    'ماتور',
  ],
  beja: [
    'باجة',
    'تبرسق',
    'نفزة',
    'مجاز الباب',
    'أم العرائس',
  ],
  jendouba: [
    'جندوبة',
    'عين دراهم',
    'فرنانة',
    'بوسالم',
    'القلعة الخصبة',
  ],
  kef: [
    'الكاف',
    'تاجروين',
    'قلعة سنان',
    'ساقية سيدي يوسف',
    'القيروان',
  ],
  siliana: [
    'سليانة',
    'برقو',
    'الكريب',
    'مكثر',
    'روغة',
  ],
  kairouan: [
    'القيروان',
    'وسلات',
    'حفوز',
    'عين جلولة',
    'سبيبة',
  ],
  kasserine: [
    'القصرين',
    'فريانة',
    'سبيبة',
    'ثيبار',
    'حيدرة',
  ],
  sidi_bouzid: [
    'سيدي بوزيد',
    'بئر الحفي',
    'جلمة',
    'مكتر',
    'السبيخة',
  ],
  sousse: [
    'سوسة',
    'أكودة',
    'حمام سوسة',
    'القنطاوي',
    'مساكن',
  ],
  monastir: [
    'المنستير',
    'قصر هلال',
    'بني حسان',
    'طبلبة',
    'الجم',
  ],
  mahdia: [
    'المهدية',
    'قصور الساف',
    'شربان',
    'أولاد الشامخ',
    'الجم',
  ],
  sfax: [
    'صفاقس',
    'ساقية الزيت',
    'سخيرة',
    'المحرس',
    'طينة',
  ],
  gafsa: [
    'قفصة',
    'الرديف',
    'المتلوي',
    'سيدي بوزيد',
    'قطار',
  ],
  tozeur: [
    'توزر',
    'نفطة',
    'تمغزة',
    'الدقاش',
    'حزوة',
  ],
  kebili: [
    'قبلي',
    'دوز',
    'سوق الأحد',
    'الفوار',
    'الجميلة',
  ],
  gabes: [
    'قابس',
    'الحامة',
    'مطماطة',
    'مارث',
    'المطوية',
  ],
  medenine: [
    'مدنين',
    'بنقردان',
    'جربة',
    'جرجيس',
    'زمورا',
  ],
  tatouine: [
    'تطاوين',
    'بني خداش',
    'رمادة',
    'الذهيبة',
    'غمراسن',
  ],
}

export function getCitiesForGovernorate(governorateId: string): string[] {
  return tunisiaCities[governorateId] || []
}

export function getGovernorateName(governorateId: string): string {
  const gov = tunisiaGovernorates.find(g => g.id === governorateId)
  return gov?.name || governorateId
}

